# Specifies the method to use for merging models.
# See: https://github.com/arcee-ai/mergekit#merge-methods

merge_method: "linear"
base_model: "./checkpoints/model_1"
models:
  - model: "./checkpoints/model_1"
    parameters:
      weight: 0.1
  - model: "./checkpoints/model_2"
    parameters:
      weight: 0.9
tokenizer_source: "./checkpoints/model_1"
dtype: "bfloat16"
